// File generated by manual configuration from google-services.json and GoogleService-Info.plist
// Do not edit this file manually unless you have manually configured Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// For each platform, values are sourced from the platform-specific
/// configuration files that were bundled with the project.
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSKUWCm0hw862czHAmDMhVjJ3D3DCWSzU',
    appId: '1:504194469723:android:df887e155742d99154547e',
    messagingSenderId: '504194469723',
    projectId: 'arvind-6d29e',
    storageBucket: 'arvind-6d29e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuIOnkS8MbjIv7Q45tKV4uLbjSY2JjAag',
    appId: '1:504194469723:ios:e72715a782a47dd754547e',
    messagingSenderId: '504194469723',
    projectId: 'arvind-6d29e',
    storageBucket: 'arvind-6d29e.firebasestorage.app',
    iosBundleId: 'com.arvindparty.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOaruqlWNUny_-SKCbW9xYBEifjegF_M',
    appId: '1:504194469723:web:91d88d32f34aa7aa54547e',
    messagingSenderId: '504194469723',
    projectId: 'arvind-6d29e',
    authDomain: 'arvind-6d29e.firebaseapp.com',
    storageBucket: 'arvind-6d29e.firebasestorage.app',
    measurementId: 'G-XW9WR262VC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuIOnkS8MbjIv7Q45tKV4uLbjSY2JjAag',
    appId: '1:504194469723:ios:a1b71d394c42ff7d54547e',
    messagingSenderId: '504194469723',
    projectId: 'arvind-6d29e',
    storageBucket: 'arvind-6d29e.firebasestorage.app',
    iosBundleId: 'com.example.arvindParty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnOaruqlWNUny_-SKCbW9xYBEifjegF_M',
    appId: '1:504194469723:web:0147a6d038ec414e54547e',
    messagingSenderId: '504194469723',
    projectId: 'arvind-6d29e',
    authDomain: 'arvind-6d29e.firebaseapp.com',
    storageBucket: 'arvind-6d29e.firebasestorage.app',
    measurementId: 'G-DYJHFW02FW',
  );
}
