// File generated by manual configuration from google-services.json and GoogleService-Info.plist
// Do not edit this file manually unless you have manually configured Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// For each platform, values are sourced from the platform-specific
/// configuration files that were bundled with the project.
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure by running the FlutterFire CLI.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure by running the FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2E3SWB2-PNJvDSnONVmw_t_JiQKwda6c',
    appId: '1:936691114067:android:e4d6a3f647ce71a85ce6a6',
    messagingSenderId: '936691114067',
    projectId: 'arvind-party-1',
    storageBucket: 'arvind-party-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxj0PUKB_M36aOs-G3uj2I6QOgeqQqJA',
    appId: '1:59307295659:ios:83ea99a01ef06f2438c8ee',
    messagingSenderId: '59307295659',
    projectId: 'arvind-party-e583b',
    storageBucket: 'arvind-party-e583b.firebasestorage.app',
    iosClientId: '59307295659-67l2civ6ltmpkpcvfhs1daegam83s19v.apps.googleusercontent.com',
    iosBundleId: 'com.arvind.party.arvindparty',
  );
}